<a href="https://colab.research.google.com/github/nagao-cs/numpy-100/blob/master/Numpy_Learnnig.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [12]:
print(a.shape)
print(a.ndim)
print(a.size)

(3,)
1
3


In [9]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(b.shape)
print(b.ndim)
print(b.size)

(3, 3)
2
9


In [13]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
c = np.full((3, 3), 9)
print(c)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [17]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
e = np.random.random((5, 4))
print(e)

[[0.4820694  0.13444454 0.80725326 0.52556287]
 [0.03074458 0.80793317 0.63572442 0.47435492]
 [0.9809397  0.4911884  0.95127493 0.91156458]
 [0.18498379 0.75436167 0.43394848 0.63343159]
 [0.40359491 0.24102127 0.37209305 0.41773671]]


In [19]:
f = np.arange(3, 10, 2)
print(f)

[3 5 7 9]


In [20]:
val = e[2, 1]
print(val)

0.01941320546862879


In [23]:
center = d[1:3, 1:4]
print(center)
print(center.shape)

[[1. 0. 0.]
 [0. 1. 0.]]
(2, 3)


In [34]:
e[1:len(e), 1:len(e[0]-2)] = 0
print(e)
print(len(e))
print(len(e[0]))

[[0.4820694  0.13444454 0.80725326 0.52556287]
 [0.03074458 0.         0.         0.        ]
 [0.9809397  0.         0.         0.        ]
 [0.18498379 0.         0.         0.        ]
 [0.40359491 0.         0.         0.        ]]
5
4


In [39]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(np.array([a[0,1], a[2,1], a[1,0]]))
print(a[[0, 2, 1], [1, 1, 0]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 8 4]
[2 8 4]


In [40]:
x = np.arange(3)
x.dtype

dtype('int64')

In [42]:
y = np.arange(3.0)
print(y)
y.dtype

[0. 1. 2.]


dtype('float64')

In [45]:
x = np.arange(1, 5, 1, dtype=np.float32)
print(x)
x.dtype

x = x.astype(np.int64)
print(x, x.dtype)

[1. 2. 3. 4.]
[1 2 3 4] int64


In [49]:
a = np.arange(1,10).reshape(3, 3)
b = np.arange(1, 10).reshape(3, 3)
c = a + b
print(c)
c = a - b
print(c)
c = a * b
print(c)
c = a / b
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
c = np.sqrt(b)
print(c)
c = np.power(b, 2)
print(c == b**2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [53]:
b = np.arange(1, 4)
c = a + b
print(c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [55]:
a = np.arange(1, 4)
print(a)
b = np.full((3), 2)
print(b)
c = a * b
print(c)
print(a * 2)

[1 2 3]
[2 2 2]
[2 4 6]
[2 4 6]


In [58]:
a = np.random.randint(0, 10, (2, 1, 3))
b = np.random.randint(0, 10, (3, 1))
print(a, a.shape)
print(b, b.shape)

c = a + b
print(c, c.shape)


[[[0 6 9]]

 [[3 0 0]]] (2, 1, 3)
[[0]
 [6]
 [0]] (3, 1)
[[[ 0  6  9]
  [ 6 12 15]
  [ 0  6  9]]

 [[ 3  0  0]
  [ 9  6  6]
  [ 3  0  0]]] (2, 3, 3)


In [59]:
print("Original b:", b.shape)
b_expand = b[np.newaxis, :, :]
print("Expanded b:", b_expand.shape)
b_expand_2 = b[:, np.newaxis, :]
print("Expanded b:", b_expand_2.shape)

Original b: (3, 1)
Expanded b: (1, 3, 1)
Expanded b: (3, 1, 1)


In [61]:
a = np.random.randint(0, 10, (5, 5))
b = np.arange(1, 6)
print(a, b)
c = np.empty((5, 5))

[[9 2 4 9 7]
 [2 0 7 5 2]
 [7 9 0 7 5]
 [6 4 1 8 0]
 [1 6 4 7 8]] [1 2 3 4 5]


In [62]:
%%timeit
for i in range(a.shape[0]):
  c[i, :] = a[i, :] + b

9.09 µs ± 2.61 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [63]:
print(c)

[[10.  4.  7. 13. 12.]
 [ 3.  2. 10.  9.  7.]
 [ 8. 11.  3. 11. 10.]
 [ 7.  6.  4. 12.  5.]
 [ 2.  8.  7. 11. 13.]]


In [64]:
%%timeit
c = a + b

The slowest run took 4.59 times longer than the fastest. This could mean that an intermediate result is being cached.
3.3 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [67]:
a = np.arange(9).reshape(3, 3)
b  =np.arange(1, 10).reshape(3, 3)
c = np.dot(a, b)
print(c)
c = a.dot(b)
print(c)
c = a @ b
print(c)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]


In [68]:
x = np.random.randint(0, 10, (8, 10))
print(x)

[[0 8 1 8 7 1 6 9 0 1]
 [0 0 4 4 9 8 5 7 4 9]
 [6 1 9 4 2 3 1 3 5 8]
 [8 4 4 2 4 5 9 6 2 6]
 [2 0 2 7 5 3 0 9 9 8]
 [5 9 3 2 0 6 9 2 9 1]
 [6 8 7 1 9 0 5 6 0 0]
 [2 7 5 7 6 4 7 6 7 8]]


In [69]:
print(x.mean())
print(x.var())
print(x.std())
print(x.max())
print(x.min())

4.6875
9.23984375
3.039711129367394
9
0


In [70]:
print(x.mean(axis=1))

[4.1 5.  4.2 5.  4.5 4.6 4.2 5.9]
